wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.8
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1673864207.746563
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      3:
      - 23
      4: 3.9.15
      5: 0.13.8
      8:
      - 3
      - 5
